version: '3'

services:
  postgres-spring-microservice:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /pg-data:/var/lib/postgresql/data 
    networks:
      - spring-microservice-network
      
  pgadmin-spring-microservice:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "elephwebb@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres-spring-microservice
    networks:
      - spring-microservice-network

networks: 
  spring-microservice-network:
    driver: bridge

